version: '3'
services:
    backend:
        image: offbeat_test
        container_name: offbeat_test
        restart: always
        links:
            - db:mysql
        depends_on:
            - db
        ports:
            - 8080:8080
        env_file: .env

    db:
        image: mysql
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${MYSQL_USERNAME}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3305:3306
